"""
Django settings for koperasi project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
import os

from pathlib import Path
from datetime import timedelta


env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
# Raises Django's ImproperlyConfigured
# exception if SECRET_KEY not in os.environ
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# False if not in os.environ because of casting above
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'apps.users.apps.UsersConfig',
    'apps.loans.apps.LoansConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # React
    "http://localhost:5173", # Vite
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    # Change this from minutes=5 to minutes=60 or days=1
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), 
    
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# AUTH_USER_MODEL = 'users.User'
MEDIA_URL = '/media/'

# Folder fisik tempat gambar disimpan
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# settings.py

JAZZMIN_SETTINGS = {
    # 1. Judul & Logo
    "site_title": "Koperasi Admin",
    "site_header": "Koperasi Syariah",
    "site_brand": "Koperasi Syariah",
    "welcome_sign": "Selamat Datang Admin",

    # 2. PENGATURAN SIDEBAR (MUNCULKAN MENU SAMPING)
    # ------------------------------------------------------------------
    "show_sidebar": True,          # Wajib True agar sidebar muncul
    "navigation_expanded": True,   # Agar menu default-nya terbuka (tidak kuncup)
    
    # 3. Kustomisasi Menu Sidebar
    # Anda bisa menyembunyikan model tertentu atau mengubah urutan
    "hide_apps": [],              # Masukkan nama app yang ingin disembunyikan
    "hide_models": [],            # Masukkan model spesifik yang ingin disembunyikan
    
    # 4. Icon Keren (Menggunakan FontAwesome)
    # Format: {"app_label.model_name": "fontawesome_icon"}
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "users.User": "fas fa-user",
        "loans.ActiveLoan": "fas fa-money-bill-wave",
        "loans.LoanApplication": "fas fa-file-invoice-dollar",
        "loans.RepaymentLog": "fas fa-history",
    },

    # 5. MENAMBAHKAN LINK CUSTOM KE DASHBOARD GRAFIK KITA
    # Ini akan membuat menu baru di sidebar khusus untuk halaman grafik tadi
    "custom_links": {
        "loans": [{
            "name": "Dashboard Laporan",  # Nama Menu
            "url": "admin-dashboard",     # Nama URL (name='admin-dashboard') di urls.py
            "icon": "fas fa-chart-pie",   # Icon Chart
            "permissions": ["loans.view_activeloan"] # Hanya muncul jika user punya izin
        }]
    },
}

# Pengaturan Tampilan UI (Opsional, agar lebih rapi)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,      # Agar sidebar tetap diam saat discroll
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "theme": "flatly",          # Pilihan tema: darkly, flatly, simplex, united
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
