# Generated by Django 5.2.8 on 2025-11-18 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenor_months_requested', models.PositiveIntegerField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=10)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='users.member')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_disbursed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenor_months', models.PositiveIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate as a percentage.', max_digits=5)),
                ('disbursement_date', models.DateField(auto_now_add=True)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_loans', to='users.member')),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_loan', to='loans.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_number', models.IntegerField(help_text='Sequential number of the payment made.')),
                ('active_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.activeloan')),
            ],
        ),
    ]
