# Generated by Django 5.2.8 on 2025-12-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_activeloan_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeloan',
            name='margin_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='activeloan',
            name='monthly_installment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='activeloan',
            name='total_repayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='activeloan',
            name='amount_disbursed',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
