# Generated by Django 5.2.8 on 2025-12-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_activeloan_margin_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrepayment',
            name='payment_number',
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
