# Generated by Django 5.2.8 on 2025-12-02 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loanrepayment_payment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
