# Generated by Django 5.2.8 on 2026-05-30 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loanrepayment_payment_date'),
        ('users', '0003_alter_token_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeloan',
            name='disbursement_date',
        ),
        migrations.AlterField(
            model_name='activeloan',
            name='amount_disbursed',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='activeloan',
            name='due_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='activeloan',
            name='margin_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='activeloan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member'),
        ),
        migrations.AlterField(
            model_name='activeloan',
            name='monthly_installment',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='activeloan',
            name='tenor_months',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='activeloan',
            name='total_repayment',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
    ]
