# Generated by Django 5.2.8 on 2026-05-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_remove_activeloan_disbursement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeloan',
            name='disbursement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
