name: Koperasi CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Create Temporary .env file
      run: |
        echo "DATABASE_URL=postgres://test_user:test_pass@db:5432/test_db" >> .env
        echo "SECRET_KEY=super-secret-ci-pipeline-key" >> .env
        echo "DJANGO_SECRET_KEY=super-secret-ci-pipeline-key" >> .env
        echo "SALT=super-secret-dummy-salt" >> .env
        echo "POSTGRES_USER=test_user" >> .env
        echo "POSTGRES_PASSWORD=test_pass" >> .env
        echo "POSTGRES_DB=test_db" >> .env

    - name: Build Docker Compose
      run: docker compose up -d --build

    - name: Sleep for 10 seconds
      run: sleep 10

    - name: Run Django Tests
      run: docker compose exec -T backend python manage.py test apps.base

    # NEW FRONTEND TEST: Run natively on the GitHub server instead of Docker
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Installs the latest standard Node version

    - name: Run React Build Test
      run: |
        cd frontend
        npm install
        npm run build